apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gifs-website
  namespace: argocd
spec:
  project: default
  destination:
    namespace: gifs-website
    server: "https://kubernetes.default.svc"
  source:
    helm:
      valueFiles:
        - values/Chart/values.yaml
    repoURL: https://github.com/Daniel-Pinhas/Gifs-Website-CD.git
    targetRevision: 0.1.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
