apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gifs-website
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/Daniel-Pinhas/Gifs-Website-CD.git
    targetRevision: HEAD
    path: Chart
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gifs-website

  syncPolicy:
    syncOptions:
      - createNamespace=true

    automated:
      selfHeal: true
      prune: true
